M48
; DRILL file {KiCad (6.0.8)} date Fri 03 Feb 2023 03:48:32 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-03T15:48:32-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X3.8114Y-2.8799
X4.039Y-2.8799
T2
X2.661Y-2.8346
X2.661Y-4.8031
X5.1413Y-2.8287
X5.1413Y-4.8031
T0
M30
